repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [commit]

      - id: ruff-format
        stages: [commit]


  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: local
        pass_filenames: false
        stages: [pre-push]